### ISSUE TITLE
Можно сохранить устаревший токен на странице My Profile

### ISSUE THREAD

**Issue by zomlik** [FinTrackhq/FinTrack#16]
**Шаги:**
1. Открыть My Profile -> API Tokens
2. Создать токен
3. Нажать редактировать
4. В поле Token expiry выбрать вчера 

Если указать дату 1900 г появится ошибка 500 SERVER ERROR

**ОР:**
Ошибка при сохранении устаревшего токена

**ФР:**
Токен сохранен

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/25974ecc-41d5-4d74-ab74-77d9157c5f03)

**Comment by zomlik** [comment]
При создании токена значение в поле Token expiry не сохраняется

**Comment by yahannes** [comment]
Bug Fixed
