### ISSUE TITLE
Нет сообщения об ошибке при вводе пробелов в поле "Пароль"  на этапе регистрации

### ISSUE THREAD

**Issue by bobkofi** [FinTrackhq/FinTrack#23]
Шаги:

1. Зайти в раздел регистрации
2. Заполнить поле "Имя"
3. Заполнить поле "E-mail"
4.  Указать в поле "Пароль" значение "       1"
5. Указать в поле "Подтвердите пароль" значение "       1"
6. Нажать кнопку "Зарегистрироваться"

ОР:
Выходит сообщение об ошибке "Пароль содержит запрещенные символы"

ФР:
Нет сообщения об ошибке.

Среда:
Windows 11, Yandex Browser Версия 24.1.0.2570 (64-bit)

**Comment by yahannes** [comment]
Bug fixed
