### ISSUE TITLE
Значение в поле Payment, отображается с запятыми, на странице Extracts

### ISSUE THREAD

**Issue by zomlik** [FinTrackhq/FinTrack#29]
**Шаги:**
1. Создать Extract
2. Перейти на страницу Extract > List

**ОР:**
В поле Payment значение отображается без запятых

**ФР:**
Значение в поле Payment отображается с запятыми

**Env:**
Win10, Chrome 121.0.6167.139

**Screenshots:**
![image](https://github.com/yahannes/FinTrack/assets/69787064/625efed2-83ba-4f86-bf9d-2424411ce4fd)

**Comment by yahannes** [comment]
bug fixed
