### ISSUE TITLE
Флаг выглядит сжатым, когда выбираешь этот язык

### ISSUE THREAD

**Issue by zomlik** [FinTrackhq/FinTrack#33]
**Шаги:**
1. Открыть https://fintrack.space/
2. Авторизоваться
3. Нажать на флаг

![image](https://github.com/FinTrackhq/FinTrack/assets/69787064/25821133-b6ab-44d9-9d7a-f4b1bef3cabf)

**Comment by yahannes** [comment]
Bug FIxed
